### ISSUE TITLE
Not "python"-esque

### ISSUE THREAD

**Issue by sandkoan** [shua1090/algos#1]
https://www.cplusplus.com/reference/list/list/

**Comment by shua1090** [comment]
Thank you for your feedback. However, it seems you misunderstood what I meant by  '"python"-esque'. I was specifically referencing
the fact that C++ list's must contain elements of the same type, whereas list's in Python are not as such. 

As per your implicit question on why I am posting this library when a perfect standard library already exists, I can only respond, "to gain experience". 

Thank you.

**Comment by sandkoan** [comment]
You are welcome.
