### ISSUE TITLE
No way you'll be able to make a hashtable without a custom hashing function

### ISSUE THREAD

**Issue by sandkoan** [shua1090/algos#2]

**Comment by shua1090** [comment]
While I may want to disagree with your feedback, I will not be using my "custom" hashing function. The hashtable is still "in the air", and I haven't decided if I'm going to pursue it; If I am, I will use an existing function, such as that of [http://www.azillionmonkeys.com/qed/hash.html](http://www.azillionmonkeys.com/qed/hash.html). 

Thank you for your feedback.

**Comment by sandkoan** [comment]
Thank you for your response.
